Feature/homework12
naumalex/SalesForce_Alexander_Naumovets pull request #1
Opened 2022-07-31 18:27 UTC by naumalex

2022-08-15 14:20 UTC, voropa requested changes

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/BasePage.java
> +  /*  public void waitForPageLoaded(String caption) {
Удалите закоментированый код

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/AccountsPage.java
> +      //  waitForPageLoaded("Accounts");
Удалите закоментированый код

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/Combobox.java
> +public class Combobox {
Вероятно этот класс должен быть в elements package, а не в pages

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/HomePage.java
> +          //  By.cssSelector("*[class~='userProfilePanel'] a[class~='logout']");
Удалите закоментированый код

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/HomePage.java
> +    public void openTabByName(String tabName) {
Удалите закоментированый код

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/Utils/AccountFactory.java
> +    public AccountFactory() {
В классе со статическими методами вам не нужен конструктор

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/Utils/LeadFactory.java
> +        Faker faker = new Faker();
Сделайте его private static final на уровне класса, чтобы не создавать новый экземпляр в каждом методе

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/Utils/Utils.java
> +    public static String buildFullAddress(String street, String city, String stateProvince,
Вроде похожий метод у вас есть в классе Address.
Тут он вам точно нужен?

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/Utils/Utils.java
> +public class Utils {
Переименуйте класс в StringUtils

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/Utils/WaitUtils.java
> +public class WaitUtils {
Обычно все вэйты делают внутри BasePage и пользуются ими во всех классах-наследниках. Вроде у вас они тоже  там есть, зачем тогда отдельный WaitUtils класс

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/elements/LightningCombobox.java
> +        catch(ElementClickInterceptedException exception) {
Луше так не делать, потому что, если у вас возникнет этот эксепшн в ходе выполнения, то вы о нем даже не узнаете
Нужно хотя бы лог написать тут

2022-08-15 14:20 UTC, voropa commented on src/test/java/pages/models/Account.java
> +   // private String fullBillingAddress;
Удалите закоментированый код

2022-08-18 20:24 UTC, naumalex commented on src/test/java/pages/models/Account.java
> +   // private String fullBillingAddress;
Fixed.

2022-08-18 21:12 UTC, naumalex commented on src/test/java/pages/elements/LightningCombobox.java
> +        catch(ElementClickInterceptedException exception) {
Исправил проблему, которая к этому эксепшену приводила (для пустых значений комбик хоть и не заполнялся, но список опций открывался) и удалил обработку эксепшена.

2022-08-18 21:23 UTC, naumalex commented on src/test/java/pages/Utils/WaitUtils.java
> +public class WaitUtils {
BaseElement не наследуется от Base Page. А если унаследовать, то нужно будет реализовывать абстрактный метод WaitForPageLoaded для каждого элемента, чего делать не хотелось, поэтому отдельный класс был создан.

2022-08-19 07:13 UTC, naumalex commented on src/test/java/pages/Utils/Utils.java
> +public class Utils {
Fixed

2022-08-19 07:17 UTC, naumalex commented on src/test/java/pages/Utils/Utils.java
> +    public static String buildFullAddress(String street, String city, String stateProvince,
Использовался в тесте для Lead, так как тест был создан раньше, чем добавлен Address объект. Это исправил, теперь Lead тоже использует Address. BuildAddress удален из StringUtils.

2022-08-19 07:28 UTC, naumalex commented on src/test/java/pages/Utils/LeadFactory.java
> +        Faker faker = new Faker();
Fixed.

2022-08-19 07:28 UTC, naumalex commented on src/test/java/pages/Utils/AccountFactory.java
> +    public AccountFactory() {
Fixed

2022-08-19 07:37 UTC, naumalex commented on src/test/java/pages/HomePage.java
> +    public void openTabByName(String tabName) {
Fixed

2022-08-19 07:37 UTC, naumalex commented on src/test/java/pages/HomePage.java
> +          //  By.cssSelector("*[class~='userProfilePanel'] a[class~='logout']");
Fixed

2022-08-19 07:40 UTC, naumalex commented on src/test/java/pages/Combobox.java
> +public class Combobox {
Устаревший класс. Удалил его.

2022-08-19 07:46 UTC, naumalex commented on src/test/java/pages/AccountsPage.java
> +      //  waitForPageLoaded("Accounts");
Fixed

2022-08-19 07:46 UTC, naumalex commented on src/test/java/pages/BasePage.java
> +  /*  public void waitForPageLoaded(String caption) {
Fixed

2022-08-21 19:16 UTC, voropa requested changes
Пожалуйста, почистите ваш код от закоментированных строк. У вас их давольно много

2022-08-21 19:16 UTC, voropa commented on src/test/java/models/Car.java
> +public class Car {
Удалите этот тестовый класс

2022-08-21 19:16 UTC, voropa commented on src/test/java/tests/SimpleTest.java
> +    public void test2() {
Удалите этот тестовый класс

2022-08-27 07:16 UTC, naumalex commented on src/test/java/models/Car.java
> +public class Car {
fixed

2022-08-27 07:16 UTC, naumalex commented on src/test/java/tests/SimpleTest.java
> +    public void test2() {
Fixed.

2022-08-27 12:22 UTC, voropa approved these changes

2022-08-29 18:52 UTC, merged